import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "./components/Layout/Header";
import localFont from "next/font/local"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const rising = localFont({
	variable: "--font-family",
	src: [
		{
			path: "./fonts/Jost-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/Jost-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/Jost-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./fonts/Jost-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},

		{
			path: "./fonts/Jost-Bold.ttf",
			weight: "700",
			style: "normal",
		},
	],
	display: "swap",
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
